language: zh
pipeline:
- name: nlp_mitie
  model: total_word_feature_extractor.dat
- name: tokenizer_jieba
- name: ner_mitie
- name: ner_synonyms
- name: intent_featurizer_mitie
- name: intent_classifier_sklearn
policies:
- name: MemoizationPolicy
- name: KerasPolicy
- name: MappingPolicy
